<a href="https://colab.research.google.com/github/nikamade/Data201_MoniqueMadinkoEpseKamgui/blob/main/assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 2 – Data Wrangling with pandas
*(Based on Class 2 – pandas for R users)*

---

## Learning Objectives
By completing this assignment, you should be able to:

- Use pandas equivalents of `dplyr` verbs:
  - `filter()` → boolean indexing / `.loc[]`
  - `mutate()` → `.assign()`
  - `group_by()` → `.groupby()`
  - `summarise()` → `.agg()`
  - `arrange()` → `.sort_values()`
- Apply boolean logic correctly using `&` and `|`
- Use **method chaining** for readable, step-by-step transformations
- Create grouped summary tables with multiple statistics

---

## Dataset

Use the provided dataset: `housing.csv`

In [9]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/Reben80/Data201/refs/heads/main/Dataset/housing.csv")

In [ ]:
df.head()

   listing_id     price         size  bedrooms neighborhood          type
0      100001  145143.0  1280.741760       1.0       Suburb     Townhouse
1      100002  152251.0  1406.283113       2.0       Uptown  SingleFamily
2      100003  148251.0  4146.825713       6.0       Suburb   MultiFamily
3      100004  177711.0  3946.599818       6.0       Suburb  SingleFamily
4      100005  155269.0  1243.751760       1.0     Downtown   MultiFamily

---

# Part A – Core Wrangling (Method Chaining Required)

Using **one chained expression**, create a summary table that:

1. Keeps only observations where `price > 250000`
2. Keeps only homes with `size > 1000`
3. Creates a new variable:
   - `price_per_sqft = price / size`
4. Groups by `neighborhood`
5. Computes:
   - mean of `price_per_sqft`
   - median of `price_per_sqft`
   - count of homes
6. Sorts the result by mean `price_per_sqft` (descending)

### Requirements
- Do NOT create intermediate variables (`df2`, `df3`, etc.)
- Use `.assign()` to create new variables
- Use `.agg()` with named aggregation
- **Do not use `reset_index()`** (we did not cover it yet)

### Output format note
After `groupby()`, pandas will put `neighborhood` in the *index*. That is OK for this assignment.
Your final output can look like a table where `neighborhood` is on the left as the index.

### Deliverable
- Paste your code
- Show the final DataFrame output

---

# Part B – Translation to dplyr

In a Markdown cell, write the equivalent **dplyr** code that performs the same transformation.

Your R pipeline should include:

- `filter()`
- `mutate()`
- `group_by()`
- `summarise()`
- `arrange()`

### Reflection (3–6 sentences)

Answer:

- Which syntax feels clearer for you — pandas chaining or dplyr pipelines?
- What feels similar between them?
- What feels different?

---

# Part C – Boolean Logic Debugging

The following code produces an error:

# Part A – Core Wrangling (Method Chaining Required)

In [13]:

new_df = (df
          .query("price > 250000 & size > 1000")
          .assign(price_per_sqft = lambda x: x["price"] / x["size"])
          .groupby("neighborhood")
          .agg(mean_price=("price_per_sqft", "mean"), median_price=("price_per_sqft", "median"), count=("price_per_sqft", "count")))
new_df.sort_values("mean_price", ascending=False)

              mean_price  median_price  count
neighborhood
Midtown       181.134071    192.039592      5
Downtown      180.429685    180.747628     10
Waterfront    173.621378    178.855043      3
Uptown        165.230425    165.060943      6
Suburb        159.556463    160.170364     14

# Part B – Translation to dplyr

new-dfr <- df |>
  filter(price > 250000 & size > 1000) |>
  mutate(price_per_sqft = price / size) |>
  group_by(neighborhood) |>
  summarise(mean_price = mean(price_per_sqft),
            median_price = median(price_per_sqft),
            count = n()) |>
  arrange(desc(mean_price))

In [ ]:
new-dfr <- df |>
  filter(price > 250000 & size > 1000) |>
  mutate(price_per_sqft = price / size) |>
  group_by(neighborhood) |>
  summarise(mean_price = mean(price_per_sqft),
            median_price = median(price_per_sqft),
            count = n()) |>
  arrange(desc(mean_price))

Reflection (3–6 sentences)
Answer:

Which syntax feels clearer for you — pandas chaining or dplyr pipelines?// ** dplyr pipelines feels more clearer for me**
What feels similar between them?// ** perform  multiple data transformations step by step here both filter,create a new column,grouped by neighborhood, summary and then sorted.**
What feels different?//**the synthax is different pandas uses dots(.) while dplyr uses the pipe operator(|>)

# Part C – Boolean Logic Debugging

In [15]:
# df[df["price"] > 250000 & df["size"] > 1000]
df[(df["price"] > 250000) & (df["size"] > 1000)]

     listing_id     price         size  bedrooms neighborhood          type
317      100318  250465.0  1992.528224       3.0       Suburb         Condo
354      100355  255893.0  1421.814232       2.0       Uptown   MultiFamily
356      100357  253996.0  1347.754467       2.0       Suburb  SingleFamily
403      100404  251772.0  1417.600377       1.0     Downtown         Condo
433      100434  257430.0  1907.426589       3.0       Suburb   MultiFamily
443      100444  250758.0  1935.927969       3.0      Midtown  SingleFamily
446      100447  255019.0  1721.371562       3.0   Waterfront         Condo
448      100449  250125.0  1694.422888       3.0     Downtown  SingleFamily
460      100461  254983.0  1698.239476       2.0       Uptown   MultiFamily
461      100462  260322.0  2556.049805       4.0     Downtown  SingleFamily
477      100478  252098.0  2156.123115       2.0       Suburb     Townhouse
484      100485  282086.0  1349.474708       2.0     Downtown   MultiFamily
490      100491  276222.0  1506.047206       2.0       Suburb         Condo
497      100498  256911.0  1429.317814       1.0       Suburb  SingleFamily
506      100507  262089.0  1364.765447       2.0      Midtown         Condo
522      100523  253100.0  1424.518768       2.0     Downtown  SingleFamily
524      100525  258972.0  1408.825383       2.0     Downtown     Townhouse
528      100529  257470.0  1295.067167       2.0       Suburb  SingleFamily
530      100531  264715.0  1133.232005       2.0       Suburb   MultiFamily
531      100532  253906.0  2424.969450       4.0       Suburb  SingleFamily
535      100536  252920.0  1671.157222       2.0      Midtown     Townhouse
536      100537  260194.0  1102.368628       1.0       Uptown     Townhouse
544      100545  254656.0  2119.048810       4.0     Downtown     Townhouse
550      100551  251879.0  1038.529087       1.0       Uptown         Condo
564      100565  270192.0  1678.484128       2.0       Suburb         Condo
566      100567  281628.0  2034.886199       2.0       Suburb  SingleFamily
570      100571  265465.0  1298.832730       1.0      Midtown     Townhouse
574      100575  251273.0  1576.694940       3.0       Suburb  SingleFamily
576      100577  268486.0  1501.137430       3.0   Waterfront     Townhouse
578      100579  256725.0  1953.355816       1.0       Suburb         Condo
580      100581  256359.0  2404.097384       4.0       Uptown  SingleFamily
582      100583  258456.0  1094.498197       1.0     Downtown         Condo
584      100585  253984.0  1310.138850       2.0   Waterfront         Condo
586      100587  250760.0  1128.812505       2.0     Downtown     Townhouse
588      100589  255567.0  1119.088940       1.0      Midtown         Condo
593      100594  267053.0  3511.067746       5.0       Uptown   MultiFamily
594      100595  273662.0  1199.007055       2.0     Downtown  SingleFamily
599      100600  257287.0  1450.981922       NaN       Suburb  SingleFamily

### Tasks

1. Fix the code.
2. Explain **why** the error occurs.
3. Rewrite the filter using `.query()` instead.

---

# Part D – Short Concept Questions

Answer briefly (2–4 sentences each):

1. Why must we wrap each condition in parentheses when using `&` in pandas?
2. What is the advantage of method chaining over creating many temporary DataFrames?
3. In `.agg(mean_price=("price", "mean"))`, what does `"price"` represent? What does `"mean"` represent?
4. When you `groupby("neighborhood")`, why does `neighborhood` appear on the left (index) in the result table?

---

## Optional Extension (Extra practice)
Create a second summary table grouped by `type` that reports:
- mean `price`
- median `price`
- count of listings
(Use method chaining again.)

The error occurs because the parentheses were missing for each condition For one variable we dont need parenthesis but for two or more we do.
i use query to rewrite it below

In [16]:
df.query("price > 250000 and size > 1000")

     listing_id     price         size  bedrooms neighborhood          type
317      100318  250465.0  1992.528224       3.0       Suburb         Condo
354      100355  255893.0  1421.814232       2.0       Uptown   MultiFamily
356      100357  253996.0  1347.754467       2.0       Suburb  SingleFamily
403      100404  251772.0  1417.600377       1.0     Downtown         Condo
433      100434  257430.0  1907.426589       3.0       Suburb   MultiFamily
443      100444  250758.0  1935.927969       3.0      Midtown  SingleFamily
446      100447  255019.0  1721.371562       3.0   Waterfront         Condo
448      100449  250125.0  1694.422888       3.0     Downtown  SingleFamily
460      100461  254983.0  1698.239476       2.0       Uptown   MultiFamily
461      100462  260322.0  2556.049805       4.0     Downtown  SingleFamily
477      100478  252098.0  2156.123115       2.0       Suburb     Townhouse
484      100485  282086.0  1349.474708       2.0     Downtown   MultiFamily
490      100491  276222.0  1506.047206       2.0       Suburb         Condo
497      100498  256911.0  1429.317814       1.0       Suburb  SingleFamily
506      100507  262089.0  1364.765447       2.0      Midtown         Condo
522      100523  253100.0  1424.518768       2.0     Downtown  SingleFamily
524      100525  258972.0  1408.825383       2.0     Downtown     Townhouse
528      100529  257470.0  1295.067167       2.0       Suburb  SingleFamily
530      100531  264715.0  1133.232005       2.0       Suburb   MultiFamily
531      100532  253906.0  2424.969450       4.0       Suburb  SingleFamily
535      100536  252920.0  1671.157222       2.0      Midtown     Townhouse
536      100537  260194.0  1102.368628       1.0       Uptown     Townhouse
544      100545  254656.0  2119.048810       4.0     Downtown     Townhouse
550      100551  251879.0  1038.529087       1.0       Uptown         Condo
564      100565  270192.0  1678.484128       2.0       Suburb         Condo
566      100567  281628.0  2034.886199       2.0       Suburb  SingleFamily
570      100571  265465.0  1298.832730       1.0      Midtown     Townhouse
574      100575  251273.0  1576.694940       3.0       Suburb  SingleFamily
576      100577  268486.0  1501.137430       3.0   Waterfront     Townhouse
578      100579  256725.0  1953.355816       1.0       Suburb         Condo
580      100581  256359.0  2404.097384       4.0       Uptown  SingleFamily
582      100583  258456.0  1094.498197       1.0     Downtown         Condo
584      100585  253984.0  1310.138850       2.0   Waterfront         Condo
586      100587  250760.0  1128.812505       2.0     Downtown     Townhouse
588      100589  255567.0  1119.088940       1.0      Midtown         Condo
593      100594  267053.0  3511.067746       5.0       Uptown   MultiFamily
594      100595  273662.0  1199.007055       2.0     Downtown  SingleFamily
599      100600  257287.0  1450.981922       NaN       Suburb  SingleFamily

# Part D – Short Concept Questions
Answer briefly (2–4 sentences each):

Why must we wrap each condition in parentheses when using & in pandas?ANSWER: **because panda does not understant the & without properly it will give an error message.**

What is the advantage of method chaining over creating many temporary DataFrames? ANSWER: **Method chaining allows multiple operations to be performed in a single pipeline**

In .agg(mean_price=("price", "mean")), what does "price" represent? What does "mean" represent? ANSWER: **Price represents a columns in a dataset while mean is the function that will calculate the average value of the price**

When you groupby("neighborhood"), why does neighborhood appear on the left (index) in the result table? ANSWER: **because it is the column that is used to create the group it is like index**

In [21]:
#Optional Extension (Extra practice)
#Create a second summary table grouped by type that reports:

#mean price
#median price
#count of listings (Use method chaining again.)
type_summary = (
    df
    .groupby("type")
    .agg(
        mean_price=("price", "mean"),
        median_price=("price", "median"),
        count=("price", "count")))
type_summary.sort_values("mean_price", ascending=False)

                 mean_price  median_price  count
type
Condo         202232.622951      197880.0    183
MultiFamily   201539.460317      204779.0     63
SingleFamily  200413.353191      201234.0    235
Townhouse     200247.050420      203287.0    119